---
name: environment-awareness
---
Jonom\EnvironmentAwareness\EnvironmentAwareness:
  environments:
    Development:
      short_label: 'DEV'
      color: '#f26522'
      description: 'Local development site'
    Stage:
      short_label: 'STAGE'
      color: '#8560a8'
      description: 'Pre-launch testing'
    Production:
      short_label: 'PROD'
      color: '#00a651'
      description: 'Live website'
